language: python
sudo: false
python:
- '2.6'
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
matrix:
  include:
  - python: 2.7
    env: JYTHON=org.python:jython-installer:2.7.0
before_install:
- if [ -n "$JYTHON" ]; then ./ci/before_install_jython.sh; source $HOME/myvirtualenv/bin/activate
  ;fi
install:
- if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
- pip install -e .
script:
- python test/testsuite.py
deploy:
  provider: pypi
  user: sunng
  password:
    secure: AiBcPz4FVeUQeGw1zJKmQVECzlxgnjKeHQXU5re6AEuedV3WkG5PrDSmzPQDcrswMw9OmuEzvJGSHi4xTD0oqS2MfAUg7phgEq14h7s4Hb2LM2vac+l6tm0JfyzZVUWqP1XeBcVpGwcONYvaxSNTVrIFGjKBK4tjkYR1Bz5RTTo=
  on:
    tags: true
    repo: jiptool/jip
  distributions: sdist bdist_wheel
